files: .*\.py
exclude: \.pylintrc
repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      args: [-l 79]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
    - id: mypy
      name: mypy
      entry: mypy
      language: system
